### ISSUE TITLE
Missing items to add to application.yml

### ISSUE THREAD

**Issue by llcawthorne** [micronaut-guides/micronaut-database-authentication-provider-groovy#6]
This didn't work for me after following the tutorial.  I had to diff what I had with the complete version to see that the tutorial forgot to tell me to add the following to application.yml.  Without it, I was getting 500's from the database failing to startup right:

```
hibernate:
    hbm2ddl:
        auto: update
dataSource:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```
